[env:uno]
platform = atmelavr
board = uno
framework = arduino
extra_scripts = pre:cnext_build.py
monitor_speed = 115200
build_flags = -I include
build_src_flags =
    -Wall
    -Wextra
    -Wno-unused-parameter
lib_deps =
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    SPI
    Wire
