/**
 * Generated by C-Next Transpiler from: VentController.cnx
 * A safer C for embedded systems
 */

#include "Domain/VentController.hpp"

#include <Arduino.h>
#include <AppConfig.hpp>

/* Scope: VentController */

void VentController__setup(void) {
    Serial.begin(AppConfig__SERIAL_BAUD);
    Serial.println("vent-controller starting");
}

void VentController__loop(void) {
}
