#ifndef VENTCONTROLLER_H
#define VENTCONTROLLER_H

/**
 * Generated by C-Next Transpiler from: VentController.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.hpp>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void VentController_setup(void);
void VentController_loop(void);

#ifdef __cplusplus
}
#endif

#endif /* VENTCONTROLLER_H */
