#ifndef CNX_SRC_DOMAIN_VENTCONTROLLER_H
#define CNX_SRC_DOMAIN_VENTCONTROLLER_H

/**
 * Generated by C-Next Transpiler from: VentController.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>
#include <AppConfig.hpp>

#ifdef __cplusplus
extern "C" {
#endif

/* Function prototypes */
void VentController__setup(void);
void VentController__loop(void);

#ifdef __cplusplus
}
#endif

#endif /* CNX_SRC_DOMAIN_VENTCONTROLLER_H */
