#ifndef APPCONFIG_H
#define APPCONFIG_H

/**
 * Generated by C-Next Transpiler from: AppConfig.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const float AppConfig_COOL_SETPOINT_DEFAULT_C;
extern const float AppConfig_HEAT_SETPOINT_DEFAULT_C;
extern const float AppConfig_HYSTERESIS_C;
extern const float AppConfig_SETPOINT_MINIMUM_C;
extern const float AppConfig_SETPOINT_MAXIMUM_C;
extern const float AppConfig_SETPOINT_STEP_C;
extern const uint32_t AppConfig_SERIAL_BAUD;

#ifdef __cplusplus
}
#endif

#endif /* APPCONFIG_H */
