#ifndef CNX_SRC_APPCONFIG_H
#define CNX_SRC_APPCONFIG_H

/**
 * Generated by C-Next Transpiler from: AppConfig.cnx
 * Header file for cross-language interoperability
 */

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* External variables */
extern const float AppConfig__COOL_SETPOINT_DEFAULT_C;
extern const float AppConfig__HEAT_SETPOINT_DEFAULT_C;
extern const float AppConfig__HYSTERESIS_C;
extern const float AppConfig__SETPOINT_MINIMUM_C;
extern const float AppConfig__SETPOINT_MAXIMUM_C;
extern const float AppConfig__SETPOINT_STEP_C;
extern const uint32_t AppConfig__SERIAL_BAUD;

#ifdef __cplusplus
}
#endif

#endif /* CNX_SRC_APPCONFIG_H */
