/**
 * Generated by C-Next Transpiler from: main.cnx
 * A safer C for embedded systems
 */

#include <Arduino.h>
#include <Domain/VentController.hpp>

void setup(void) {
    VentController_setup();
}

void loop(void) {
    VentController_loop();
}
